spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/9d64dfab-644d-4ee5-9620-934b52f48ab5
#          issuer-uri: https://login.microsoftonline.com/9d64dfab-644d-4ee5-9620-934b52f48ab5/v2.0/.well-known/openid-configuration
#          jwk-set-uri: https://login.microsoftonline.com/9d64dfab-644d-4ee5-9620-934b52f48ab5/discovery/v2.0/keys
          audience: api://425cae19-a568-407c-a25f-91f7fb243070/access_as_user


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
